/* Geverifieerde golfclubs per provincie (bron: NGF-banenzoeker golf.nl,
   Lijst van golfbanen in Nederland, en de clubs zelf).
   Puur feitelijk: deze clubs liggen in deze provincie. Géén claim over
   optredens, klantrelaties of samenwerking. */
export const GOLFCLUBS = {
  groningen: [
    ['Noord-Nederlandse Golf & Country Club', 'Glimmen'],
    ['Golfclub De Compagnie', 'Veendam'],
    ['Groningse Golfclub Duurswold', 'Steendam'],
    ['Golfclub Westerwolde', 'Vlagtwedde'],
  ],
  friesland: [
    ['Golf & Country Club Lauswolt', 'Beetsterzwaag'],
    ['Leeuwarder Golfclub De Groene Ster', 'Leeuwarden'],
    ['Golfclub Heidemeer', 'Heerenveen'],
    ['Golfclub Gaasterland', 'Oudemirdum'],
    ['Golfpark Sint Nyk', 'Sint Nicolaasga'],
    ['Golfbaan Ameland', 'Hollum'],
  ],
  drenthe: [
    ['Drentsche Golf & Country Club', 'Assen'],
    ['Drentse Golfclub De Gelpenberg', 'Aalden'],
    ['Golfparc Sandur', 'Emmen'],
    ['Golfclub Havelte', 'Havelte'],
    ['Golfclub De Semslanden', 'Gasselternijveen'],
    ['Golfclub Martensplek', 'Tiendeveen'],
  ],
  overijssel: [
    ['Twentsche Golfclub', 'Ambt Delden'],
    ["Sallandsche Golfclub 'De Hoek'", 'Diepenveen'],
    ['Golfclub Zwolle', 'Zwolle'],
    ['Het Rijk van Sybrook', 'Enschede'],
    ['Hooge Graven Golfclub Ommen', 'Ommen'],
    ['Golfclub De Koepel', 'Wierden'],
    ['Enschedese Golfclub Prinses Wilhelmina', 'Enschede'],
  ],
  flevoland: [
    ['Golfclub Almeerderhout', 'Almere'],
    ['Golfbaan Dorhout Mees', 'Biddinghuizen'],
    ['Golfclub Flevoland', 'Lelystad'],
    ['Golfclub Emmeloord', 'Emmeloord'],
    ['Golfclub Zeewolde', 'Zeewolde'],
    ['Golfclub Golfresidentie Dronten', 'Dronten'],
  ],
  gelderland: [
    ['Rosendaelsche Golfclub', 'Arnhem'],
    ['The Dutch', 'Spijk'],
    ['Het Rijk van Nijmegen', 'Groesbeek'],
    ['Het Rijk van Nunspeet', 'Nunspeet'],
    ['Edese Golf Club Papendal', 'Arnhem'],
    ['Wageningse Golfclub', 'Wageningen'],
    ['Veluwse Golfclub', 'Hoog Soeren'],
    ['Lochemse Golfclub', 'Lochem'],
  ],
  utrecht: [
    ['Utrechtse Golfclub De Pan', 'Bosch en Duin'],
    ['Golfsociëteit De Lage Vuursche', 'Den Dolder'],
    ['Golfclub Anderstein', 'Maarsbergen'],
    ['Golfclub De Hoge Kleij', 'Leusden'],
    ['De Goyer Golf & Country Club', 'Eemnes'],
    ['Golfclub De Haar', 'Haarzuilens'],
    ['Doornsche Golf Club', 'Doorn'],
  ],
  'noord-holland': [
    ['Kennemer Golf & Country Club', 'Zandvoort'],
    ['Hilversumsche Golf Club', 'Hilversum'],
    ['The International', 'Badhoevedorp'],
    ['Amsterdamse Golf Club', 'Halfweg'],
    ['Haarlemmermeersche Golfclub', 'Cruquius'],
    ['Golfbaan Spaarnwoude', 'Velsen-Zuid'],
    ['De Texelse', 'De Cocksdorp'],
    ['Westfriese Golfclub', 'Westwoud'],
  ],
  'zuid-holland': [
    ['Koninklijke Haagsche Golf & Country Club', 'Wassenaar'],
    ['Noordwijkse Golfclub', 'Noordwijk'],
    ['Rijswijkse Golfclub', 'Rijswijk'],
    ['Golfclub Broekpolder', 'Vlaardingen'],
    ['Golfclub Cromstrijen', 'Numansdorp'],
    ['Golfclub Oude Maas', 'Rhoon'],
    ['De Hooge Rotterdamsche', 'Bergschenhoek'],
    ['Golfclub Zeegersloot', 'Alphen aan den Rijn'],
  ],
  zeeland: [
    ['De Goese Golf', 'Goes'],
    ['Golfclub Grevelingenhout', 'Bruinisse'],
    ['Domburgsche Golfclub', 'Domburg'],
    ['De Zeeuwsche', 'Middelburg'],
    ['Golfbaan De Brugse Vaart', 'Oostburg'],
    ['Golfvereniging De Woeste Kop', 'Axel'],
  ],
  'noord-brabant': [
    ['Eindhovensche Golf', 'Valkenswaard'],
    ['Bernardus Golf', 'Cromvoirt'],
    ['Golfclub De Dommel', 'Sint-Michielsgestel'],
    ['Noord-Brabantsche Golfclub Toxandria', 'Molenschot'],
    ['Oosterhoutse Golf Club', 'Oosterhout'],
    ['Golf Club Prise d’Eau', 'Tilburg'],
    ['The Duke Club', 'Nistelrode'],
    ['Golfclub Wouwse Plantage', 'Bergen op Zoom'],
  ],
  limburg: [
    ['De Zuid Limburgse Golf & Country Club Wittem', 'Gulpen-Wittem'],
    ['Golf-Resort Brunssummerheide', 'Brunssum'],
    ['Hoenshuis Golf', 'Voerendaal'],
    ['International Golf Maastricht', 'Maastricht'],
    ['Golf- & Countryclub Geijsteren', 'Geysteren'],
    ['De Herkenbosche', 'Melick-Herkenbosch'],
    ['Crossmoor Golf', 'Weert'],
    ['Het Rijk van Margraten', 'Cadier en Keer'],
  ],
};
