/* Pillar: golfshows. Bilinguale, unieke SEO-content over de golf trickshows van Mark Reynolds.
   Interne links blijven NL-paden; de generator prefixt ze met /en voor de EN-versie. */
export default {
  slug: 'golfshows',
  ico: 'target',
  videoId: 'uA4HTbv6gYU',
  related: ['golftrips', 'golfballen-bedrijfsgolfdag'],
  nl: {
    video: {
      sub: 'Op zoek naar een onvergetelijke golfbeleving? De golf trickshow van Mark Reynolds combineert skill, precisie en entertainment die elk publiek versteld doet staan — van verbluffende trickshots tot precisieslagen die je niet gelooft tot je ze ziet.',
      videoTitle: 'All golfers MUST watch — Golf Trick Show | Mark Reynolds',
      feats: [
        { ico: 'target', t: 'Ongelofelijke trickshots', s: 'Slagen die de zwaartekracht lijken te tarten.' },
        { ico: 'users', t: 'Perfect voor events', s: 'Bedrijfsevents, relatiedagen en golfdagen.' },
        { ico: 'chat', t: 'Skill, humor & interactie', s: 'Mark betrekt het publiek er volop bij.' },
        { ico: 'check', t: 'Op maat voor jouw event', s: 'De show wordt afgestemd op de gelegenheid.' },
      ],
    },
    name: 'Golfshows',
    crumb: 'Golfshows',
    metaTitle: 'Golfshow boeken met PGA-pro Mark Reynolds | MrGolfbal.nl',
    metaDesc: 'Golfshow of golf trickshow boeken voor je bedrijfsevent, golfdag of clubjubileum? PGA-professional Mark Reynolds brengt trickshots, skill en humor. Boek in NL en Europa.',
    eyebrow: 'Pillar · Trick Pro',
    h1: 'Golfshow boeken met <span>PGA-professional Mark Reynolds</span>',
    lead: 'Een golfshow zet een event op scherp: verrassende trickshots, echte vakmanschap en een flinke dosis humor. Mark Reynolds — PGA-professional en meervoudig winnaar — is te boeken voor golfclubs en bedrijven in Nederland, Europa en daarbuiten.',
    intro: `<p class="lead">Zoek je een moment dat je gasten écht bijblijft? Een golfshow — ook wel golf trickshow genoemd — is een van de meest visuele en verrassende manieren om een golfdag, bedrijfsevent of clubjubileum kracht bij te zetten. In korte tijd zien je gasten wat er met een golfbal allemaal mogelijk is: van slagen die de wetten van de logica lijken te tarten tot verhalen van binnen de professionele golfsport. Op deze pagina lees je precies wat een golfshow inhoudt, voor welke gelegenheden hij werkt, wat je gasten kunnen verwachten en hoe je Mark Reynolds boekt.</p>
    <p>De golfshows worden verzorgd door <a href="/over-mark/">Mark Reynolds</a>, PGA-professional sinds 1995 en oprichter van MrGolfbal.nl. Als "Trick Pro" combineert hij tientallen jaren toernooiervaring met een aanstekelijke show die zowel de doorgewinterde golfer als de complete leek weet te raken. Boeken kan voor vrijwel elke locatie: een golfclub, een drivingrange, een bedrijfsterrein of een evenementenhal — in Nederland, elders in Europa en op aanvraag ver daarbuiten.</p>`,
    sections: [
      { h: 'Wat is een golfshow of golf trickshow?', html: `<p>Een golfshow is een live-optreden waarin een golfprofessional laat zien wat er met techniek, timing en creativiteit mogelijk is met een golfclub en een bal. Waar een gewone demonstratie zich beperkt tot nette slagen, gaat een <strong>golf trickshow</strong> een stap verder: bijzondere ballen, ongewone clubs, slagen vanuit onmogelijke standen en momenten die je gasten hardop laten lachen of verbaasd laten kijken. Het is entertainment met een kern van echt vakmanschap — geen goochelarij, maar jarenlang geslepen skill die er moeiteloos uitziet.</p>
      <p>Belangrijk: een goede golfshow draait niet alleen om de slagen zelf, maar om het verhaal eromheen. Mark neemt zijn publiek mee door de show met uitleg, anekdotes en interactie, zodat ook wie nog nooit een club vasthield begrijpt waar hij naar kijkt. Zo wordt <strong>golf entertainment</strong> toegankelijk voor een gemengd gezelschap van klanten, medewerkers en relaties. Wil je de show combineren met actief zelf spelen, dan is een aansluitende clinic een natuurlijke vervolgstap — daarover verderop meer.</p>` },
      { h: 'Voor welke gelegenheden werkt een golfshow?', html: `<p>Een golfshow is verrassend flexibel en past bij uiteenlopende momenten. De meest gevraagde gelegenheden zijn:</p>
      <p><strong>Bedrijfsevents en relatiedagen.</strong> Een golfshow tijdens een <a href="/toepassingen/golfballen-bedrijfsgolfdag/">bedrijfsgolfdag</a> of relatie-evenement geeft het programma een professioneel hoogtepunt. Terwijl je gasten toch al op de baan zijn, brengt de show een gedeeld moment dat de dag samenbindt en gespreksstof oplevert voor aan tafel.</p>
      <p><strong>Clubjubilea en ledenevenementen.</strong> Voor golfclubs is een golfshow een dankbare invulling van een jubileum, een openingsdag of een ledenfeest. Het is een cadeau aan de leden dat past bij de sport zelf en dat generaties golfers samen laat genieten.</p>
      <p><strong>Baanopeningen en sponsorevents.</strong> Bij de opening van een nieuwe baan, een gerenoveerde hole of een sponsoractivatie geeft een show glans aan het moment en trekt hij aandacht van pers en publiek. Ook bij productlanceringen — waar golf als thema of decor dient — voegt een trickshow een onverwacht en deelbaar element toe.</p>
      <p>Kortom: overal waar mensen samenkomen rond golf, of waar je een event een sportieve, verrassende twist wilt geven, is een golfshow op zijn plaats. Twijfel je of jouw gelegenheid past? Leg je situatie voor via <a href="/contact/">contact</a> — Mark denkt eerlijk met je mee.</p>` },
      { h: 'Wat kunnen je gasten verwachten?', html: `<p>Een golfshow van Mark draait om drie ingrediënten die samen de beleving maken. Ten eerste de <strong>trickshots</strong>: slagen die je gasten niet snel ergens anders zien, uitgevoerd met controle en timing die alleen uit jarenlange ervaring komt. Ten tweede de <strong>skill</strong>: de nauwkeurigheid en het balgevoel van een professional die op het hoogste amateurs- en pro-niveau heeft gespeeld, zichtbaar van dichtbij. En ten derde de <strong>humor en interactie</strong>: Mark betrekt zijn publiek erbij, speelt in op reacties en houdt de toon licht, zodat de show voor iedereen leuk blijft — of je nu single handicap speelt of nog nooit hebt afgeslagen.</p>
      <p>Wat je precies te zien krijgt, stemmen we af op je gezelschap, de locatie en de tijd die beschikbaar is. De exacte invulling en duur van de show bespreken we vooraf, zodat het optreden past bij je programma <span class="confirm-tag">(duur en precieze inhoud in overleg te bepalen)</span>. Zo weet je zeker dat de show aansluit op de rest van je dag en op de verwachtingen van je gasten.</p>` },
      { h: 'Golfshow combineren met een golfclinic', html: `<p>Veel opdrachtgevers kiezen ervoor de show te combineren met een <strong>golfclinic</strong>. De logica is aantrekkelijk: eerst kijken je gasten hun ogen uit tijdens de show, en daarna mogen ze het zelf proberen onder begeleiding van dezelfde professional. Die volgorde werkt: de show breekt het ijs en maakt enthousiast, de clinic maakt het persoonlijk en actief.</p>
      <p>In een clinic krijgen je gasten in kleine groepen uitleg over de basis — houding, grip, en de eerste swing — met korte, opbouwende tips die meteen resultaat geven. Voor ervaren golfers kan de focus juist liggen op een specifiek onderdeel van hun spel. Omdat Mark PGA-professional is en dagelijks lesgeeft, is die begeleiding vakkundig en persoonlijk. Wil je clinic en show samen inzetten voor een bedrijfsdag, bekijk dan ook de mogelijkheden rond een complete <a href="/toepassingen/golfballen-bedrijfsgolfdag/">bedrijfsgolfdag</a>.</p>` },
      { h: 'Waarom Mark Reynolds boeken?', html: `<p>Een golfshow staat of valt met de professional die hem geeft. Mark Reynolds combineert entertainment met een staat van dienst die weinigen kunnen evenaren. Hij is <strong>PGA-professional sinds 1995</strong> en deed zijn PGA-opleiding onder Simon Thornhill bij Rotherham Golf Club in Engeland. Geboren in 1978 in Maltby (Rotherham), begon hij op zijn vijfde met golf en verhuisde in 2000 naar Nederland, waar hij in 2001 een golfschool oprichtte bij Golf Centrum Noordwijk. Sinds 2014 is hij verbonden aan The International golf club bij Badhoevedorp (Amsterdam).</p>
      <p>Zijn erelijst onderstreept het niveau: winnaar van de Nederlandse PGA Order of Merit in <strong>2005, 2009 en 2018</strong>, winnaar van het European PGA Team Championship in <strong>2019</strong> en van de PGA Cup (Groot-Brittannië & Ierland tegen de VS) in <strong>2005</strong>. Hij speelde het KLM Open — in 2018 als best geklasseerde Nederlandse speler — en heeft meer dan tien professionele toernooioverwinningen op zijn naam. Die geloofwaardigheid vertaalt zich in een show die niet alleen vermaakt, maar ook indruk maakt. Meer over zijn achtergrond lees je op <a href="/over-mark/">de pagina over Mark</a>.</p>` },
      { h: 'Hoe werkt het boeken van een golfshow?', html: `<p>Een golfshow boeken begint met een gesprek. Je laat weten om wat voor gelegenheid het gaat, waar en wanneer het plaatsvindt, hoeveel gasten je verwacht en of je de show eventueel wilt combineren met een clinic. Op basis daarvan stemt Mark de invulling af en ontvang je een voorstel op maat. Prijzen en beschikbaarheid zijn afhankelijk van datum, locatie en de gewenste opzet <span class="confirm-tag">(tarief en beschikbaarheid op aanvraag)</span>.</p>
      <p>Omdat Mark bookbaar is voor golfclubs en bedrijven in Nederland, elders in Europa en op aanvraag daarbuiten, is het verstandig om vroeg contact op te nemen — zeker voor data in het drukke golfseizoen. Vraag je golfshow aan via <a href="/contact/">de contactpagina</a>. Overweeg je naast de show ook een meerdaagse golfbeleving? Bekijk dan de <a href="/golftrips/">golftrips met Mark</a>, of ontdek hoe je je event compleet maakt met <a href="/golfballen-bedrukken-voor-bedrijven/">bedrukte golfballen voor bedrijven</a>. Alle zakelijke toepassingen vind je gebundeld onder <a href="/toepassingen/">toepassingen</a>.</p>` },
    ],
    faq: [
      ['Wat is het verschil tussen een golfshow en een golf trickshow?', 'De termen worden vaak door elkaar gebruikt. Een golfshow is de bredere noemer voor golf entertainment; een golf trickshow legt de nadruk op verrassende trickshots. Bij Mark krijg je in de praktijk beide: skill, trickshots, verhaal en interactie in één optreden.'],
      ['Voor wie is een golfshow geschikt?', 'Voor vrijwel elk gezelschap. Doordat Mark de show begeleidt met uitleg en humor, genieten zowel ervaren golfers als mensen die nog nooit een club vasthielden. Ideaal voor bedrijfsevents, golfdagen, clubjubilea, baanopeningen en sponsorevents.'],
      ['Kan ik een golfshow combineren met een clinic?', 'Ja, dat is een veelgevraagde combinatie. Eerst kijken je gasten naar de show, daarna spelen ze zelf onder begeleiding van Mark in een golfclinic. Zo wordt het een actieve en persoonlijke beleving.'],
      ['Waar is Mark Reynolds te boeken?', 'Mark is bookbaar voor golfclubs en bedrijven in Nederland, elders in Europa en op aanvraag ook daarbuiten. Neem vroeg contact op voor data in het hoogseizoen.'],
      ['Hoe lang duurt een golfshow?', 'De duur stemmen we af op je programma, je gezelschap en de locatie. De precieze opzet en tijdsduur bespreken we vooraf, zodat de show naadloos in je dag past.'],
      ['Hoe boek ik een golfshow met Mark Reynolds?', 'Neem contact op via de contactpagina met de datum, locatie, het aantal gasten en je wensen. Je ontvangt dan een voorstel op maat; tarief en beschikbaarheid zijn op aanvraag.'],
    ],
    bookH: 'Golfshow boeken voor jouw event?',
    bookP: 'Zet je golfdag, bedrijfsevent of clubjubileum kracht bij met een golfshow van PGA-professional Mark Reynolds. Laat je datum, locatie en wensen weten via de contactpagina en ontvang een voorstel op maat.',
  },
  en: {
    video: {
      sub: 'Looking for an unforgettable golf experience? Mark Reynolds’ golf trick show combines skill, precision and entertainment that amazes any audience — from jaw-dropping trick shots to precision strikes you won’t believe until you see them.',
      videoTitle: 'All golfers MUST watch — Golf Trick Show | Mark Reynolds',
      feats: [
        { ico: 'target', t: 'Incredible trick shots', s: 'Shots that seem to defy gravity.' },
        { ico: 'users', t: 'Perfect for events', s: 'Corporate events, client days and golf days.' },
        { ico: 'chat', t: 'Skill, humour & interaction', s: 'Mark draws the whole audience in.' },
        { ico: 'check', t: 'Tailored to your event', s: 'The show is shaped around the occasion.' },
      ],
    },
    name: 'Golf shows',
    crumb: 'Golf shows',
    metaTitle: 'Book a golf show with PGA pro Mark Reynolds | MrGolfbal.nl',
    metaDesc: 'Book a golf show or golf trick show for your company event, golf day or club anniversary. PGA professional Mark Reynolds brings trick shots, skill and humour across Europe.',
    eyebrow: 'Pillar · Trick Pro',
    h1: 'Book a golf show with <span>PGA professional Mark Reynolds</span>',
    lead: 'A golf show sharpens any event: surprising trick shots, genuine craft and a good dose of humour. Mark Reynolds — PGA professional and multiple winner — can be booked for golf clubs and companies in the Netherlands, across Europe and beyond.',
    intro: `<p class="lead">Looking for a moment your guests will genuinely remember? A golf show — also called a golf trick show — is one of the most visual and surprising ways to lift a golf day, company event or club anniversary. In a short time your guests see just what is possible with a golf ball: from shots that seem to defy logic to stories from inside professional golf. This page explains exactly what a golf show involves, which occasions it suits, what your guests can expect and how to book Mark Reynolds.</p>
    <p>The golf shows are delivered by <a href="/over-mark/">Mark Reynolds</a>, a PGA professional since 1995 and founder of MrGolfbal.nl. As the "Trick Pro" he combines decades of tournament experience with an infectious show that reaches the seasoned golfer and the complete newcomer alike. He can be booked for almost any venue: a golf club, a driving range, a company site or an events hall — in the Netherlands, elsewhere in Europe and, on request, well beyond.</p>`,
    sections: [
      { h: 'What is a golf show or golf trick show?', html: `<p>A golf show is a live performance in which a golf professional demonstrates what is possible with technique, timing and creativity using a club and a ball. Where an ordinary demonstration sticks to tidy shots, a <strong>golf trick show</strong> goes further: unusual balls, uncommon clubs, shots from impossible stances and moments that make your guests laugh out loud or watch in disbelief. It is entertainment with a core of real craft — no conjuring, but years of honed skill that looks effortless.</p>
      <p>Importantly, a good golf show is not only about the shots themselves, but about the story around them. Mark carries his audience through the show with explanation, anecdotes and interaction, so that even someone who has never held a club understands what they are watching. That makes <strong>golf entertainment</strong> accessible to a mixed audience of clients, staff and relations. If you would like to combine the show with active play, a follow-up clinic is a natural next step — more on that below.</p>` },
      { h: 'Which occasions does a golf show suit?', html: `<p>A golf show is surprisingly flexible and fits a wide range of moments. The most-requested occasions are:</p>
      <p><strong>Company events and relation days.</strong> A golf show during a <a href="/toepassingen/golfballen-bedrijfsgolfdag/">company golf day</a> or client event gives the programme a professional highlight. While your guests are already on the course, the show creates a shared moment that binds the day together and provides talking points over dinner.</p>
      <p><strong>Club anniversaries and member events.</strong> For golf clubs, a golf show is a rewarding way to mark an anniversary, an opening day or a members' celebration. It is a gift to the members that suits the sport itself and lets generations of golfers enjoy it together.</p>
      <p><strong>Course openings and sponsor events.</strong> At the opening of a new course, a renovated hole or a sponsor activation, a show adds shine to the moment and draws the attention of press and public. At product launches too — where golf serves as a theme or backdrop — a trick show adds an unexpected and shareable element.</p>
      <p>In short: wherever people gather around golf, or wherever you want to give an event a sporty, surprising twist, a golf show is at home. Not sure whether your occasion fits? Put your situation to us via <a href="/contact/">contact</a> — Mark will give you honest advice.</p>` },
      { h: 'What can your guests expect?', html: `<p>Mark's golf show revolves around three ingredients that together make the experience. First, the <strong>trick shots</strong>: shots your guests will not soon see elsewhere, executed with control and timing that only years of experience bring. Second, the <strong>skill</strong>: the precision and ball feel of a professional who has played at the highest amateur and pro level, visible up close. And third, the <strong>humour and interaction</strong>: Mark draws his audience in, responds to reactions and keeps the tone light, so the show stays enjoyable for everyone — whether you play off a single-figure handicap or have never teed off.</p>
      <p>Exactly what you will see is tailored to your audience, the venue and the time available. We agree the precise content and duration of the show in advance, so the performance fits your programme <span class="confirm-tag">(duration and precise content to be agreed in consultation)</span>. That way you can be sure the show connects with the rest of your day and with your guests' expectations.</p>` },
      { h: 'Combining a golf show with a golf clinic', html: `<p>Many clients choose to combine the show with a <strong>golf clinic</strong>. The logic is appealing: first your guests watch in amazement during the show, and afterwards they get to try it themselves under the guidance of the same professional. That order works: the show breaks the ice and builds enthusiasm, the clinic makes it personal and active.</p>
      <p>In a clinic your guests receive, in small groups, an explanation of the basics — posture, grip and the first swing — with short, constructive tips that deliver immediate results. For experienced golfers, the focus can instead fall on a specific part of their game. Because Mark is a PGA professional who teaches daily, that guidance is expert and personal. If you want to combine clinic and show for a corporate day, do also look at the options around a complete <a href="/toepassingen/golfballen-bedrijfsgolfdag/">company golf day</a>.</p>` },
      { h: 'Why book Mark Reynolds?', html: `<p>A golf show stands or falls with the professional who delivers it. Mark Reynolds combines entertainment with a track record few can match. He has been a <strong>PGA professional since 1995</strong> and completed his PGA training under Simon Thornhill at Rotherham Golf Club in England. Born in 1978 in Maltby (Rotherham), he started golf at the age of five and moved to the Netherlands in 2000, where he founded a golf school at Golf Centrum Noordwijk in 2001. Since 2014 he has been based at The International golf club near Badhoevedorp (Amsterdam).</p>
      <p>His honours underline the level: winner of the Dutch PGA Order of Merit in <strong>2005, 2009 and 2018</strong>, winner of the European PGA Team Championship in <strong>2019</strong> and of the PGA Cup (Great Britain & Ireland versus the USA) in <strong>2005</strong>. He has played the KLM Open — in 2018 as the best-placed Dutch player — and has more than ten professional tournament wins to his name. That credibility translates into a show that not only entertains, but also impresses. You can read more about his background on <a href="/over-mark/">the about Mark page</a>.</p>` },
      { h: 'How does booking a golf show work?', html: `<p>Booking a golf show starts with a conversation. You let us know what kind of occasion it is, where and when it takes place, how many guests you expect and whether you would like to combine the show with a clinic. On that basis Mark tailors the content and you receive a bespoke proposal. Prices and availability depend on the date, venue and the desired format <span class="confirm-tag">(fee and availability on request)</span>.</p>
      <p>Because Mark can be booked for golf clubs and companies in the Netherlands, elsewhere in Europe and, on request, beyond, it is wise to get in touch early — certainly for dates in the busy golf season. Request your golf show via <a href="/contact/">the contact page</a>. Considering a multi-day golf experience alongside the show? Then look at the <a href="/golftrips/">golf trips with Mark</a>, or discover how to round off your event with <a href="/golfballen-bedrukken-voor-bedrijven/">printed golf balls for businesses</a>. You will find all business applications gathered under <a href="/toepassingen/">applications</a>.</p>` },
    ],
    faq: [
      ['What is the difference between a golf show and a golf trick show?', 'The terms are often used interchangeably. A golf show is the broader label for golf entertainment; a golf trick show emphasises surprising trick shots. With Mark you get both in practice: skill, trick shots, story and interaction in one performance.'],
      ['Who is a golf show suitable for?', 'Almost any audience. Because Mark guides the show with explanation and humour, both experienced golfers and people who have never held a club can enjoy it. Ideal for company events, golf days, club anniversaries, course openings and sponsor events.'],
      ['Can I combine a golf show with a clinic?', 'Yes, that is a popular combination. First your guests watch the show, then they play themselves under Mark\'s guidance in a golf clinic. That makes it an active and personal experience.'],
      ['Where can Mark Reynolds be booked?', 'Mark can be booked for golf clubs and companies in the Netherlands, elsewhere in Europe and, on request, beyond. Get in touch early for dates in the peak season.'],
      ['How long does a golf show last?', 'We tailor the duration to your programme, your audience and the venue. We agree the precise format and length in advance, so the show fits seamlessly into your day.'],
      ['How do I book a golf show with Mark Reynolds?', 'Get in touch via the contact page with the date, venue, number of guests and your wishes. You will then receive a bespoke proposal; fee and availability are on request.'],
    ],
    bookH: 'Book a golf show for your event?',
    bookP: 'Give your golf day, company event or club anniversary a lift with a golf show by PGA professional Mark Reynolds. Share your date, venue and wishes via the contact page and receive a bespoke proposal.',
  },
};
