/* Pillar: golftrips. Bilinguale, unieke SEO-content over golfreizen met PGA-pro Mark Reynolds (Travel Pro).
   Interne links blijven NL-paden; de generator prefixt ze met /en voor de EN-versie. */
export default {
  slug: 'golftrips',
  ico: 'flag',
  related: ['golfshows', 'golfballen-relatiegeschenk'],
  nl: {
    name: 'Golftrips',
    crumb: 'Golftrips',
    metaTitle: 'Golfreis met PGA-pro boeken — Travel Pro Mark Reynolds | MrGolfbal.nl',
    metaDesc: 'Golfreis met een PGA-professional erbij? Mark Reynolds regelt coaching op locatie, organisatie en groepsbeleving voor bedrijven, vriendengroepen en clubs. Vraag je golftrip aan.',
    eyebrow: 'Pillar · Travel Pro',
    h1: 'Golfreis boeken met <span>PGA-professional Mark Reynolds</span>',
    lead: 'Een golfreis wordt beter met een pro erbij: coaching op de baan, een strak georganiseerd programma en een groepsbeleving die blijft hangen. Mark Reynolds neemt als "Travel Pro" je golftrip onder zijn hoede — voor bedrijven, vriendengroepen en clubs.',
    intro: `<p class="lead">Een golfreis is meer dan een aantal rondjes op een mooie baan. Het is de combinatie van sport, ontspanning en samenzijn — en juist die combinatie tilt een goede golftrip boven een gewone vakantie uit. Neem je een PGA-professional mee, dan komt daar een dimensie bij: je speelt niet alleen, je wordt ook beter, en de organisatie ligt in ervaren handen. Op deze pagina lees je wat een golfreis met een pro toevoegt, voor wie het bedoeld is, wat er te regelen valt en hoe je bij Mark Reynolds een golftrip aanvraagt.</p>
    <p>De golfreizen vallen onder de "Travel Pro"-service van <a href="/over-mark/">Mark Reynolds</a>, PGA-professional sinds 1995 en oprichter van MrGolfbal.nl. Als reisbegeleider met een indrukwekkende toernooicarrière combineert hij vakinhoudelijke coaching met het gemak van een goed geregelde trip. Of je nu met collega's, vrienden of clubleden op pad gaat, in Nederland, elders in Europa of daarbuiten — een golfreis met Mark is sportief, sociaal en zorgeloos.</p>`,
    sections: [
      { h: 'Wat voegt een golfreis met een pro toe?', html: `<p>Het verschil tussen een golfreis op eigen houtje en een golftrip met een professional zit in drie dingen. Ten eerste de <strong>coaching op locatie</strong>. In plaats van thuis een les te nemen en die op de baan te vergeten, krijg je begeleiding op het moment dat het telt: tijdens het spelen, op de holes die je uitdagen. Een korte aanwijzing bij de afslag, een blik op je putting, een tip over strategie — kleine dingen die tijdens een reis van meerdere dagen echt beklijven.</p>
      <p>Ten tweede de <strong>organisatie</strong>. Een golfreis heeft veel losse onderdelen: baanreserveringen, flights indelen, het programma laten aansluiten op ieders niveau. Wanneer een ervaren pro dat mee vormgeeft, hoef je je daar zelf niet druk over te maken. Ten derde de <strong>groepsbeleving</strong>. Golf verbindt, en een goed begeleide reis maakt daar het maximale van: gedeelde successen op de baan, ontspanning eromheen en een gelijk speelveld waarop iedereen — van beginner tot lage handicap — zich thuis voelt.</p>` },
      { h: 'Voor wie is een golftrip met Mark bedoeld?', html: `<p>Een golfreis met een pro past bij verschillende gezelschappen, elk met een eigen accent.</p>
      <p><strong>Bedrijven en incentives.</strong> Wil je klanten belonen, relaties verstevigen of een team belonen voor een goed jaar? Een zakelijke golfreis is een krachtige incentive: je bent samen weg, je deelt de baan, en de informele momenten leveren de gesprekken op die op kantoor niet ontstaan. De aanwezigheid van een PGA-professional geeft de trip bovendien cachet.</p>
      <p><strong>Vriendengroepen.</strong> Voor golfvrienden die er samen even tussenuit willen, is een golftrip met begeleiding de manier om zowel te genieten als te verbeteren. Je speelt de banen die je zelf niet snel zou boeken, met iemand die je onderweg scherper maakt.</p>
      <p><strong>Golfclubs en verenigingen.</strong> Een clubreis onder begeleiding van een pro is een geliefde traditie. Leden van uiteenlopend niveau reizen samen, spelen samen en krijgen onderweg praktische coaching. Zo wordt een clubuitje ook een moment van gezamenlijke vooruitgang.</p>` },
      { h: 'Wat kan er geregeld worden?', html: `<p>De opzet van een golfreis is maatwerk, afgestemd op je gezelschap, je wensen en je budget. In grote lijnen kan Mark meedenken over de baankeuze en het speelschema, over de indeling van flights en niveaus, over coachingmomenten tijdens de reis en over de balans tussen golf en ontspanning. Het idee is dat je gasten zich kunnen richten op spelen en genieten, terwijl het sportieve programma doordacht in elkaar zit.</p>
      <p>Concrete bestemmingen, data en verblijfsvormen bepalen we samen — die zijn afhankelijk van je gezelschap, het seizoen en je voorkeuren <span class="confirm-tag">(bestemming, reisduur en programma in overleg samen te stellen)</span>. Sommige groepen kiezen voor dichtbij en kort, andere voor een langere reis verder weg. Wat de vorm ook wordt, het uitgangspunt blijft hetzelfde: een golftrip die sportief klopt en sociaal werkt. Wil je de reis compleet maken met een aandenken voor de deelnemers, denk dan aan <a href="/golfballen-personaliseren/">gepersonaliseerde golfballen</a> of een <a href="/golfballen-bedrukken/">bedrukte golfbal</a> als herinnering.</p>` },
      { h: 'Coaching en beleving op de baan', html: `<p>Het hart van een golfreis met Mark is wat er op de baan gebeurt. Anders dan een losse les werkt coaching tijdens een meerdaagse trip cumulatief: een aanwijzing op dag één die je op dag twee al terugziet in je spel. Doordat Mark je gedurende de reis meemaakt in echte spelsituaties, kan hij zijn advies afstemmen op wat jij op dat moment nodig hebt — of dat nu je lange spel, je korte spel of je mentale aanpak is.</p>
      <p>Tegelijk blijft een golfreis een reis: het draait ook om plezier, om de holes die je bijblijven en om de avonden na afloop. Mark bewaakt die balans. Wie wil werken aan zijn spel krijgt daar volop ruimte voor; wie vooral wil genieten van het samenzijn, wordt niet lastiggevallen met te veel techniek. Die flexibiliteit maakt een golftrip geschikt voor gemengde gezelschappen waarin niet iedereen even fanatiek is.</p>` },
      { h: 'Waarom Mark Reynolds als reisbegeleider?', html: `<p>Een golfreis met een pro is zo goed als de pro die meegaat. Mark Reynolds is <strong>PGA-professional sinds 1995</strong> en deed zijn PGA-opleiding onder Simon Thornhill bij Rotherham Golf Club in Engeland. Geboren in 1978 in Maltby (Rotherham), begon hij op zijn vijfde met golf en verhuisde in 2000 naar Nederland. Daar richtte hij in 2001 een golfschool op bij Golf Centrum Noordwijk en sinds 2014 is hij verbonden aan The International golf club bij Badhoevedorp (Amsterdam).</p>
      <p>Zijn palmares spreekt voor zich: winnaar van de Nederlandse PGA Order of Merit in <strong>2005, 2009 en 2018</strong>, winnaar van het European PGA Team Championship in <strong>2019</strong> en van de PGA Cup (Groot-Brittannië & Ierland tegen de VS) in <strong>2005</strong>. Hij speelde het KLM Open — in 2018 als best geklasseerde Nederlandse speler — en boekte meer dan tien professionele toernooioverwinningen. Belangrijker voor een reis: hij geeft dagelijks les en weet hoe hij spelers van elk niveau vooruithelpt, met geduld en humor. Lees meer op <a href="/over-mark/">de pagina over Mark</a>.</p>` },
      { h: 'Hoe vraag je een golfreis aan?', html: `<p>Een golftrip aanvragen begint vrijblijvend. Je laat weten met wat voor gezelschap je op reis wilt, hoe groot de groep is, welk niveau de deelnemers hebben en wat je ongeveer voor ogen hebt qua bestemming, periode en duur. Op basis daarvan denkt Mark met je mee en werkt hij een voorstel uit dat past bij jullie wensen en budget. Beschikbaarheid, prijs en programma zijn afhankelijk van je keuzes <span class="confirm-tag">(offerte en beschikbaarheid op aanvraag)</span>.</p>
      <p>Omdat een goede golfreis vraagt om planning — banen reserveren, agenda's afstemmen, het programma opbouwen — is het verstandig ruim van tevoren contact op te nemen. Vraag je golftrip aan via <a href="/contact/">de contactpagina</a>. Zoek je naast de reis ook vermaak voor een event thuis? Bekijk dan de <a href="/golfshows/">golfshows met Mark</a>. En wil je je gasten verrassen met een blijvend aandenken, lees dan over golfballen als <a href="/golfballen-bedrukken-voor-bedrijven/">zakelijk relatiegeschenk</a>.</p>` },
    ],
    faq: [
      ['Wat maakt een golfreis met een pro anders dan een gewone golfvakantie?', 'Bij een golftrip met een PGA-professional krijg je coaching op locatie, een doordacht georganiseerd programma en een groepsbeleving die verbindt. Je speelt niet alleen mooie banen, je wordt onderweg ook beter.'],
      ['Voor wie is een golftrip met Mark geschikt?', 'Voor bedrijven en incentives, voor vriendengroepen en voor golfclubs of verenigingen. Doordat de begeleiding zich aanpast aan het niveau, voelen zowel beginners als lage handicaps zich thuis.'],
      ['Bepaalt Mark de bestemming?', 'Nee, bestemming, periode en reisduur stellen we samen vast, afgestemd op je gezelschap, het seizoen en je voorkeuren. Mark denkt mee over baankeuze, programma en de balans tussen golf en ontspanning.'],
      ['Krijgt iedereen in de groep coaching?', 'Coaching is beschikbaar voor wie eraan wil werken en past zich aan per speler. Wie vooral wil genieten van het samenzijn, wordt niet overladen met techniek. Die flexibiliteit maakt de reis geschikt voor gemengde groepen.'],
      ['Kan een golfreis zakelijk worden ingezet als incentive?', 'Zeker. Een zakelijke golfreis is een sterke incentive voor klanten, relaties of teams: je bent samen weg, deelt de baan en de informele momenten leveren waardevolle gesprekken op.'],
      ['Hoe vraag ik een golftrip met Mark Reynolds aan?', 'Neem vrijblijvend contact op via de contactpagina met je gezelschap, groepsgrootte, niveau en globale wensen. Je ontvangt dan een voorstel op maat; prijs en beschikbaarheid zijn op aanvraag.'],
    ],
    bookH: 'Golfreis met een pro aanvragen?',
    bookP: 'Van een zakelijke incentive tot een clubreis of een trip met golfvrienden — PGA-professional Mark Reynolds maakt er een sportieve, zorgeloze golfreis van. Vraag vrijblijvend een voorstel aan via de contactpagina.',
  },
  en: {
    name: 'Golf trips',
    crumb: 'Golf trips',
    metaTitle: 'Book a golf trip with a PGA pro — Travel Pro Mark Reynolds | MrGolfbal.nl',
    metaDesc: 'A golf trip with a PGA professional along? Mark Reynolds arranges on-course coaching, organisation and a group experience for companies, friends and clubs. Enquire now.',
    eyebrow: 'Pillar · Travel Pro',
    h1: 'Book a golf trip with <span>PGA professional Mark Reynolds</span>',
    lead: 'A golf trip is better with a pro along: coaching on the course, a tightly organised programme and a group experience that stays with you. As the "Travel Pro", Mark Reynolds takes your golf trip under his wing — for companies, groups of friends and clubs.',
    intro: `<p class="lead">A golf trip is more than a few rounds on a beautiful course. It is the combination of sport, relaxation and togetherness — and it is precisely that combination that lifts a good golf trip above an ordinary holiday. Bring a PGA professional along and a further dimension is added: you do not just play, you also improve, and the organisation is in experienced hands. This page explains what a golf trip with a pro adds, who it is for, what can be arranged and how to enquire about a golf trip with Mark Reynolds.</p>
    <p>The golf trips fall under the "Travel Pro" service of <a href="/over-mark/">Mark Reynolds</a>, a PGA professional since 1995 and founder of MrGolfbal.nl. As a trip host with an impressive tournament career, he combines expert coaching with the ease of a well-organised trip. Whether you set off with colleagues, friends or club members, in the Netherlands, elsewhere in Europe or beyond — a golf trip with Mark is sporting, sociable and carefree.</p>`,
    sections: [
      { h: 'What does a golf trip with a pro add?', html: `<p>The difference between a golf trip on your own and a golf trip with a professional comes down to three things. First, the <strong>coaching on location</strong>. Instead of taking a lesson at home and forgetting it on the course, you get guidance at the moment that counts: while you play, on the holes that challenge you. A short pointer at the tee, a glance at your putting, a tip on strategy — small things that, over a trip of several days, genuinely stick.</p>
      <p>Second, the <strong>organisation</strong>. A golf trip has many separate parts: course reservations, arranging flights, matching the programme to everyone's level. When an experienced pro helps shape that, you do not have to worry about it yourself. Third, the <strong>group experience</strong>. Golf connects people, and a well-hosted trip makes the most of that: shared successes on the course, relaxation around it and a level field on which everyone — from beginner to low handicap — feels at home.</p>` },
      { h: 'Who is a golf trip with Mark for?', html: `<p>A golf trip with a pro suits a range of groups, each with its own emphasis.</p>
      <p><strong>Companies and incentives.</strong> Want to reward clients, strengthen relations or thank a team for a good year? A business golf trip is a powerful incentive: you are away together, you share the course, and the informal moments spark the conversations that do not happen at the office. The presence of a PGA professional also lends the trip cachet.</p>
      <p><strong>Groups of friends.</strong> For golfing friends who want to get away together, a hosted golf trip is the way to both enjoy and improve. You play the courses you would not readily book yourself, with someone who sharpens your game along the way.</p>
      <p><strong>Golf clubs and societies.</strong> A club trip hosted by a pro is a cherished tradition. Members of varying levels travel together, play together and receive practical coaching en route. That turns a club outing into a moment of shared progress too.</p>` },
      { h: 'What can be arranged?', html: `<p>The set-up of a golf trip is bespoke, tailored to your group, your wishes and your budget. Broadly, Mark can help think through the course choice and playing schedule, the arrangement of flights and levels, coaching moments during the trip and the balance between golf and relaxation. The idea is that your guests can focus on playing and enjoying themselves, while the sporting programme is thoughtfully put together.</p>
      <p>Concrete destinations, dates and forms of stay we decide together — these depend on your group, the season and your preferences <span class="confirm-tag">(destination, trip length and programme to be put together in consultation)</span>. Some groups opt for close by and short, others for a longer trip further afield. Whatever the form, the starting point stays the same: a golf trip that works sportingly and socially. If you would like to round off the trip with a keepsake for the participants, consider <a href="/golfballen-personaliseren/">personalised golf balls</a> or a <a href="/golfballen-bedrukken/">printed golf ball</a> as a memento.</p>` },
      { h: 'Coaching and the experience on the course', html: `<p>The heart of a golf trip with Mark is what happens on the course. Unlike a one-off lesson, coaching during a multi-day trip works cumulatively: a pointer on day one that you already see back in your game on day two. Because Mark experiences you throughout the trip in real playing situations, he can tailor his advice to what you need at that moment — whether that is your long game, your short game or your mental approach.</p>
      <p>At the same time, a golf trip remains a trip: it is also about enjoyment, about the holes that stay with you and about the evenings afterwards. Mark keeps that balance. Those who want to work on their game get plenty of room for it; those who mainly want to enjoy the company are not burdened with too much technique. That flexibility makes a golf trip suitable for mixed groups in which not everyone is equally keen.</p>` },
      { h: 'Why choose Mark Reynolds as your trip host?', html: `<p>A golf trip with a pro is only as good as the pro who comes along. Mark Reynolds has been a <strong>PGA professional since 1995</strong> and completed his PGA training under Simon Thornhill at Rotherham Golf Club in England. Born in 1978 in Maltby (Rotherham), he started golf at the age of five and moved to the Netherlands in 2000. There he founded a golf school at Golf Centrum Noordwijk in 2001, and since 2014 he has been based at The International golf club near Badhoevedorp (Amsterdam).</p>
      <p>His record speaks for itself: winner of the Dutch PGA Order of Merit in <strong>2005, 2009 and 2018</strong>, winner of the European PGA Team Championship in <strong>2019</strong> and of the PGA Cup (Great Britain & Ireland versus the USA) in <strong>2005</strong>. He has played the KLM Open — in 2018 as the best-placed Dutch player — and has recorded more than ten professional tournament wins. More important for a trip: he teaches daily and knows how to move players of every level forward, with patience and humour. Read more on <a href="/over-mark/">the about Mark page</a>.</p>` },
      { h: 'How do you enquire about a golf trip?', html: `<p>Enquiring about a golf trip starts with no obligation. You let us know what kind of group you want to travel with, how large the group is, what level the participants are and roughly what you have in mind for destination, period and duration. On that basis Mark thinks along with you and works out a proposal that suits your wishes and budget. Availability, price and programme depend on your choices <span class="confirm-tag">(quote and availability on request)</span>.</p>
      <p>Because a good golf trip calls for planning — reserving courses, coordinating diaries, building the programme — it is wise to get in touch well in advance. Enquire about your golf trip via <a href="/contact/">the contact page</a>. Looking for entertainment for an event at home as well as the trip? Then look at the <a href="/golfshows/">golf shows with Mark</a>. And if you would like to surprise your guests with a lasting keepsake, read about golf balls as a <a href="/golfballen-bedrukken-voor-bedrijven/">corporate gift for businesses</a>.</p>` },
    ],
    faq: [
      ['What makes a golf trip with a pro different from an ordinary golf holiday?', 'On a golf trip with a PGA professional you get coaching on location, a thoughtfully organised programme and a group experience that connects. You do not just play fine courses, you also improve along the way.'],
      ['Who is a golf trip with Mark suitable for?', 'For companies and incentives, for groups of friends and for golf clubs or societies. Because the guidance adapts to the level, both beginners and low handicaps feel at home.'],
      ['Does Mark decide the destination?', 'No, destination, period and trip length are set together, tailored to your group, the season and your preferences. Mark helps think through course choice, programme and the balance between golf and relaxation.'],
      ['Does everyone in the group get coaching?', 'Coaching is available for those who want to work on their game and adapts per player. Those who mainly want to enjoy the company are not overloaded with technique. That flexibility makes the trip suitable for mixed groups.'],
      ['Can a golf trip be used as a business incentive?', 'Certainly. A business golf trip is a strong incentive for clients, relations or teams: you are away together, share the course, and the informal moments produce valuable conversations.'],
      ['How do I enquire about a golf trip with Mark Reynolds?', 'Get in touch without obligation via the contact page with your group, group size, level and rough wishes. You will then receive a bespoke proposal; price and availability are on request.'],
    ],
    bookH: 'Enquire about a golf trip with a pro?',
    bookP: 'From a business incentive to a club trip or a getaway with golfing friends — PGA professional Mark Reynolds turns it into a sporting, carefree golf trip. Request a proposal without obligation via the contact page.',
  },
};
